platform :ios, '9.0'
inhibit_all_warnings!

target 'SPLogExample' do
  use_frameworks!

  # Pods for SPLogExample
pod 'SPLog', :path => '../'

  target 'SPLogExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
